@Fx_SQL_ServiceAPIs_HostAddress = http://localhost:5050

GET {{Fx_SQL_ServiceAPIs_HostAddress}}/hello-world/

###
POST {{Fx_SQL_ServiceAPIs_HostAddress}}/security/createToken/
Accept: application/json
{
    "UserName":"srg",
    "Password":"srg"
}

###
GET {{Fx_SQL_ServiceAPIs_HostAddress}}/weather-forecast/
Accept: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiR2FuZXNoIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoic3IuZ2FuZXNoQHN1bnRveW8uY29tIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiIxMCIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcHJpbWFyeXNpZCI6IjEwIiwiQ29tcGFueSI6IkZTeCIsImV4cCI6MTcxMzY5NTk0OSwiaXNzIjoiRmlyZUNsb3VkIFNlcnZpY2UiLCJhdWQiOiJGaXJlQ2xvdWQgU2VydmljZSJ9.Ys-91jpFNItqFtV0L5A42qXC89eM4z6MhI2O7SnxTiU-qC3XzDoNCuV96YXIAI2Q3Oc-ddUViRo7dqnbcLaJe3_3G6HH6xnfNzRL76FsrobyoOpMCqbnvIKAYoSgDJHKHTVE7boswm5ljCf82Gp8VoH_XDJSwQ5tS1XtmBN-M39aBvxQSuU6HFQ6TCstWZghQk6RdSj-ffueKjyOfGh-h1f0pwmz5W8qbJIYFIxujrhaI06FMwEbGwp35IKUb7NJK5BL7emH7YTUyyFwfP0BIGgPEGpCNz_za0zwP5o99ZlEvWiemhsw5LGQVlQYkEGWLbwXe8M6swfpl8AHnSE81Q-XXXXX

###
POST {{Fx_SQL_ServiceAPIs_HostAddress}}/mssql-api/dms/test/create/
Accept: application/json
Content-Type: application/json
{
  "C1": "Field 7",
  "C2": "Field 8",
  "Age": "45"
}

###
POST {{Fx_SQL_ServiceAPIs_HostAddress}}/mssql-api/dms/test/average/age
Accept: application/json
Content-Type: application/json
[]


###
POST {{Fx_SQL_ServiceAPIs_HostAddress}}/sqlite-api/dms.db/test/create/
Accept: application/json
Content-Type: application/json
{
  "Id": "1",
  "C1": "Field 7",
  "C2": "Field 8",
  "Age": "45"
}


###
POST {{Fx_SQL_ServiceAPIs_HostAddress}}/mssql-api/dms/user/create/
Accept: application/json
Content-Type: application/json
{
  "UserName": "SR Ganesh Ram",
  "Password": "System!232-Age35",
  "Salt": "Age35",
  "AccessToken":"dfsdfXmd090do-ol9kldk-MKLSdfiklos==",
  "RefreshToken":"sdfsdfklodlold-md090do-ol9kldk-MKLSdfiklos==",
  "IsSysAdmin":"true",
  "LastLogin":"09-05-2024",
  "ExpiresIn":"20",
  "ExpiresOn":"2054",
  "Deleted":"false"
}

###

PUT {{Fx_SQL_ServiceAPIs_HostAddress}}/mssql-api/dms/user/update-field/
Action: Update
Update-Fields: Salt,ExpiresIn,ExpiresOn
Accept: application/json
Content-Type: application/json
{
    "Id": "1",
    "Salt": "Age15",    
    "ExpiresIn":"30",
    "ExpiresOn":"2024"
}

###
PUT {{Fx_SQL_ServiceAPIs_HostAddress}}/mssql-api/dms/user/update-all/
Action: Update
Accept: application/json
Content-Type: application/json
{
    "Id": "1",
    "UserName": "SR Ganesh Ram",
    "Password": "Laptop!232-Age35",
    "Salt": "Age235",
    "AccessToken":"dfsdfXmd090do-ol9kldk-MKLSdfiklos==",
    "RefreshToken":"sdfsdfklodlold-md090do-ol9kldk-MKLSdfiklos==",
    "IsSysAdmin":"true",
    "LastLogin":"09-05-2024",
    "ExpiresIn":"20",
    "ExpiresOn":"2054",
    "Deleted":"false"
}



###
DELETE {{Fx_SQL_ServiceAPIs_HostAddress}}/mssql-api/dms/test/delete/1
Action: Delete
X-SOFT-DELETE: false
Accept: application/json
Content-Type: application/json


###
POST {{Fx_SQL_ServiceAPIs_HostAddress}}/mssql-api/dms/TestNumerics/create/
Accept: application/json
Content-Type: application/json
{  
  "Numeric": "7485874",
  "SmallInt": "12545",
  "TinyInt": "142",
  "Decimal":"4524552.23",
  "Float":"155863.23",
  "Money":"4589393331"
}

###
POST {{Fx_SQL_ServiceAPIs_HostAddress}}/mssql-api/dms/TestDates/create/
Accept: application/json
Content-Type: application/json
{  
  "Date": "10-04-2024",
  "DateTime": "02-11-2024 03:52:52",
  "Bit":"false"
}

###
GET {{Fx_SQL_ServiceAPIs_HostAddress}}/mssql-api/dms/TestDates/get/5
Filter: Get-By-Id
Accept: application/json
Content-Type: application/json

###
POST {{Fx_SQL_ServiceAPIs_HostAddress}}/mssql-api/dms/TestDates/get-one/
Accept: application/json
Content-Type: application/json
{  
  "Field": "Date",
  "Value": "2024-10-05",
  "Condition":"eq"
}

###
POST {{Fx_SQL_ServiceAPIs_HostAddress}}/mssql-api/dms/TestDates/get-by-page/
Accept: application/json
Content-Type: application/json
{  
  "Field": "Date",
  "Value": "2024-10-04",
  "Condition":"eq"
}
###

POST {{Fx_SQL_ServiceAPIs_HostAddress}}/mssql-api/dms/TestDates/get-by-filter/
Filter: Both-And-OR-Test
Accept: application/json
Content-Type: application/json
{
    "Fields":["Id","Date","DateTime","Bit"],
    "Sort":
    [        
        {
            "Field": "Date",
            "OrderBy":"Descending"
        }
    ],
    "Filter":
    [
        {
            "And":[
                {
                    "Field":"Date",
                    "Value":"2024-10-04",
                    "Condition":"eq"
                }
            ],
            "Or":[
                {
                    "Field":"Bit",
                    "Value":"true",
                    "Condition":"eq"
                }
            ]
        }
    ],
    "Page":0,
    "RowsPerBatch":5
}


###
POST {{Fx_SQL_ServiceAPIs_HostAddress}}/mssql-api/dms/TestDates/get-by-filter/
Filter: No-Field-Test
Accept: application/json
Content-Type: application/json
{
    "Sort":
    [        
        {
            "Field": "Date",
            "OrderBy":"Descending"
        }
    ],
    "Filter":[],
    "Page":0,
    "RowsPerBatch":5
}


###
POST {{Fx_SQL_ServiceAPIs_HostAddress}}/mssql-api/dms/TestDates/get-by-filter/
Filter: No-Filter-Test
Accept: application/json
Content-Type: application/json
{
    "Fields":["Id","Date","DateTime","Bit"],
    "Sort":
    [        
        {
            "Field": "Date",
            "OrderBy":"Descending"
        }
    ],
    "Filter":[],
    "Page":0,
    "RowsPerBatch":25
}

###
POST {{Fx_SQL_ServiceAPIs_HostAddress}}/mssql-api/dms/TestDates/get-by-filter/
Filter: Only-OR-Test
Accept: application/json
Content-Type: application/json
{
    "Fields":["Id","Date","DateTime","Bit"],
    "Sort":
    [        
        {
            "Field": "Date",
            "OrderBy":"Descending"
        }
    ],
    "Filter":[
        {    
            "Or":[
                {
                    "Field":"Bit",
                    "Value":"false",
                    "Condition":"eq"
                }
            ]
        }
    ],
    "Page":0,
    "RowsPerBatch":25
}


###
POST {{Fx_SQL_ServiceAPIs_HostAddress}}/mssql-api/dms/TestDates/get-by-filter/
Filter: Only-AND-Test
Accept: application/json
Content-Type: application/json
{
    "Fields":["Id","Date","DateTime","Bit"],
    "Sort":
    [        
        {
            "Field": "Date",
            "OrderBy":"Descending"
        }
    ],
    "Filter":[
        {    
            "Or":[
                {
                    "Field":"Bit",
                    "Value":"false",
                    "Condition":"eq"
                }
            ]
        }
    ],
    "Page":0,
    "RowsPerBatch":25
}


###
GET {{Fx_SQL_ServiceAPIs_HostAddress}}/exception

###

