@Fx_SQL_ServiceAPIs_HostAddress = http://localhost:5295

GET {{Fx_SQL_ServiceAPIs_HostAddress}}/weatherforecast/
Accept: application/json


###
POST {{Fx_SQL_ServiceAPIs_HostAddress}}/mssql-api/dms/test/create/
Accept: application/json
Content-Type: application/json
{
  "C1": "Field 3",
  "C2": "Field 4",
  "Age": "33"
}

###
POST {{Fx_SQL_ServiceAPIs_HostAddress}}/mssql-api/dms/user/create/
Accept: application/json
Content-Type: application/json
{
  "UserName": "SR Ganesh Ram",
  "Password": "System!232-Age35",
  "Salt": "Age35",
  "AccessToken":"dfsdfXmd090do-ol9kldk-MKLSdfiklos==",
  "RefreshToken":"sdfsdfklodlold-md090do-ol9kldk-MKLSdfiklos==",
  "IsSysAdmin":"true",
  "LastLogin":"09-05-2024",
  "ExpiresIn":"20",
  "ExpiresOn":"2054",
  "Deleted":"false"
}

###

PUT {{Fx_SQL_ServiceAPIs_HostAddress}}/mssql-api/dms/user/update/
Action: Update
Accept: application/json
Content-Type: application/json
{
    "Id": "1",
    "UserName": "SR Ganesh Ram",
    "Password": "Laptop!232-Age35",
    "Salt": "Age235",
    "AccessToken":"dfsdfXmd090do-ol9kldk-MKLSdfiklos==",
    "RefreshToken":"sdfsdfklodlold-md090do-ol9kldk-MKLSdfiklos==",
    "IsSysAdmin":"true",
    "LastLogin":"09-05-2024",
    "ExpiresIn":"20",
    "ExpiresOn":"2054",
    "Deleted":"false"
}


###
DELETE {{Fx_SQL_ServiceAPIs_HostAddress}}/mssql-api/dms/test/delete/1
Action: Delete
X-SOFT-DELETE: false
Accept: application/json
Content-Type: application/json


###
POST {{Fx_SQL_ServiceAPIs_HostAddress}}/mssql-api/dms/TestNumerics/create/
Accept: application/json
Content-Type: application/json
{  
  "Numeric": "7485874",
  "SmallInt": "12545",
  "TinyInt": "142",
  "Decimal":"4524552.23",
  "Float":"155863.23",
  "Money":"4589393331"
}

###
POST {{Fx_SQL_ServiceAPIs_HostAddress}}/mssql-api/dms/TestDates/create/
Accept: application/json
Content-Type: application/json
{  
  "Date": "10-04-2024",
  "DateTime": "02-11-2024 03:52:52",
  "Bit":"false"
}

###
GET {{Fx_SQL_ServiceAPIs_HostAddress}}/mssql-api/dms/TestDates/get/5
Filter: Get-By-Id
Accept: application/json
Content-Type: application/json

###
POST {{Fx_SQL_ServiceAPIs_HostAddress}}/mssql-api/dms/TestDates/get-one/
Accept: application/json
Content-Type: application/json
{  
  "Field": "Date",
  "Value": "2024-10-05",
  "Condition":"eq"
}

###
POST {{Fx_SQL_ServiceAPIs_HostAddress}}/mssql-api/dms/TestDates/get-by-page/
Accept: application/json
Content-Type: application/json
{  
  "Field": "Date",
  "Value": "2024-10-04",
  "Condition":"eq"
}
###

POST {{Fx_SQL_ServiceAPIs_HostAddress}}/mssql-api/dms/TestDates/get-by-filter/
Filter: Both-And-OR-Test
Accept: application/json
Content-Type: application/json
{
    "Fields":["Id","Date","DateTime","Bit"],
    "Sort":
    [        
        {
            "Field": "Date",
            "OrderBy":"Descending"
        }
    ],
    "Filter":
    [
        {
            "And":[
                {
                    "Field":"Date",
                    "Value":"2024-10-04",
                    "Condition":"eq"
                }
            ],
            "Or":[
                {
                    "Field":"Bit",
                    "Value":"true",
                    "Condition":"eq"
                }
            ]
        }
    ],
    "Page":0,
    "RowsPerBatch":5
}


###
POST {{Fx_SQL_ServiceAPIs_HostAddress}}/mssql-api/dms/TestDates/get-by-filter/
Filter: No-Field-Test
Accept: application/json
Content-Type: application/json
{
    "Sort":
    [        
        {
            "Field": "Date",
            "OrderBy":"Descending"
        }
    ],
    "Filter":[],
    "Page":0,
    "RowsPerBatch":5
}


###
POST {{Fx_SQL_ServiceAPIs_HostAddress}}/mssql-api/dms/TestDates/get-by-filter/
Filter: No-Filter-Test
Accept: application/json
Content-Type: application/json
{
    "Fields":["Id","Date","DateTime","Bit"],
    "Sort":
    [        
        {
            "Field": "Date",
            "OrderBy":"Descending"
        }
    ],
    "Filter":[],
    "Page":0,
    "RowsPerBatch":25
}

###
POST {{Fx_SQL_ServiceAPIs_HostAddress}}/mssql-api/dms/TestDates/get-by-filter/
Filter: Only-OR-Test
Accept: application/json
Content-Type: application/json
{
    "Fields":["Id","Date","DateTime","Bit"],
    "Sort":
    [        
        {
            "Field": "Date",
            "OrderBy":"Descending"
        }
    ],
    "Filter":[
        {    
            "Or":[
                {
                    "Field":"Bit",
                    "Value":"false",
                    "Condition":"eq"
                }
            ]
        }
    ],
    "Page":0,
    "RowsPerBatch":25
}


###
POST {{Fx_SQL_ServiceAPIs_HostAddress}}/mssql-api/dms/TestDates/get-by-filter/
Filter: Only-AND-Test
Accept: application/json
Content-Type: application/json
{
    "Fields":["Id","Date","DateTime","Bit"],
    "Sort":
    [        
        {
            "Field": "Date",
            "OrderBy":"Descending"
        }
    ],
    "Filter":[
        {    
            "Or":[
                {
                    "Field":"Bit",
                    "Value":"false",
                    "Condition":"eq"
                }
            ]
        }
    ],
    "Page":0,
    "RowsPerBatch":25
}


###
GET {{Fx_SQL_ServiceAPIs_HostAddress}}/exception

###

